version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    groups:
      companion:
        patterns:
          - '@companion-module/*'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
